### ISSUE TITLE
INTEGRATION ERROR

### ISSUE THREAD

**Issue by amo74** [corvis/homeassistant_prana#4]
Hi.

When i add integration, in the log i find this:

Error occurred loading configuration flow for integration prana: cannot import name 'IDX_IDENTIFIERS' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)

**Comment by corvis** [comment]
Hi @amo74 

This is due to incompatibility with HomeAssistant >= 2021.5. Fixed in version `0.2.0` released today.

**Comment by amo74** [comment]
Thank you
